name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Remplacez par la branche à partir de laquelle vous souhaitez déployer

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (si nécessaire)
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install # Si vous utilisez npm ou yarn pour gérer les dépendances

      - name: Build
        run: npm run build # Commande pour générer les fichiers statiques de votre site

      - name: Deploy to GitHub Pages
        uses: jamesives/github-pages-deploy-action@v4 # Utilisation de la version v4 stable
        with:
          branch: gh-pages # Branche sur laquelle déployer
          folder: build # Dossier contenant les fichiers à déployer (à ajuster selon votre configuration)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
